# Generated by Django 6.0.1 on 2026-01-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Name')),
                ('text', models.TextField(verbose_name='Note text')),
                ('reminder', models.DateTimeField(blank=True, null=True, verbose_name='Reminder')),
                ('category', models.CharField(choices=[('PER', 'Personal'), ('WRK', 'Work'), ('STU', 'Study'), ('OTH', 'Etc')], default='OTH', max_length=3, verbose_name='Category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
